wandb_version: 1

learning_rate_1:
  desc: null
  value: 1.0e-06
learning_rate_2:
  desc: null
  value: 1.0e-06
learning_rate_3:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 126
memory_size:
  desc: null
  value: 100000
episode:
  desc: null
  value: 2000
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688609487.940641
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.5
      8:
      - 5
